#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
pkill polybar
polybar &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
#bspc config window_gap          3

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr
bspc rule -a mpv state=floating
bspc rule -a feh state=floating

